project: my-gcp-project
job_name: null
service_account: null  # Service account email to run the job
location: us-central1
staging_bucket: gs://my-staging-bucket
experiment: object-detection-exp
machine_type: n1-standard-8
accelerator_type: NVIDIA_TESLA_T4
accelerator_count: 1
tensorboard_resource_name: "projects/deep-ego/locations/us-central1/tensorboards/6022053772631474176"
dry_run: true
