project: my-gcp-project
job_name: null
service_account: null  # Service account email to run the job
location: us-east1
staging_bucket: gs://my-staging-bucket
experiment: object-detection-exp
machine_type: g2-standard-8
accelerator_type: NVIDIA_L4
accelerator_count: 1
tensorboard_resource_name: null
dry_run: true
